baseURL = "/"
languageCode = "en-us"
DefaultContentLanguage = "en"
title = "App Transformation Cookbook"
copyright = "@2019, Pivotal Software, Inc. All Rights Reserved, Confidential"
theme = "hugo-theme-docdock"
publishDir = "public"
pygmentsCodeFences = true
pygmentsStyle = "friendly"

[params]
  themeStyle = "original"
  disableHomeIcon = true
  description = "Migrating applications to Cloud Foundry."
  noCategoryLink = true
  showVisitedLinks = false
  noSearch = false
  noHomeIcon = true
  ordersectionsby = "weight"
  ignoreFiles = [ "\\.adoc$" ]
  disableNavChevron = true

[outputs]
home = [ "HTML", "RSS", "JSON"]

[[menu.shortcuts]]
pre = "<h5>&nbsp;</h5>"
name = "<i class='fa fa-tag'></i>  See All Tags"
url = "/tags"
