---
platform: linux

image_resource:
  type: docker-image
  source: {repository: cloudfoundry/cflinuxfs2 }

params:
  SITE_USER:
  SITE_PASSWORD:

inputs:
  - name: cookbook-template-repo
  
outputs:
  - name: password-site

run:
  path: cookbook-template-repo/ci/tasks/htpasswd.sh
