node {
    stage('Preparation') { // for display purposes
        // Get some code from a GitHub repository
        git('https://github.com/kkester/my-cookbook.git')
        sh('git submodule update --init --recursive')
    }
    stage('Build') {
        // Run the publish
        sh('./publish')
    }
    stage("Deploy") {
        sh('cf push')
    }
}
